/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Awesome API (--base-config TEST)
 * Auto generated by fs-api
 * OpenAPI spec version: 1.2.3 (--base-config TEST)
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type GetRouteParams = {
version?: string;
};

export interface PostRouteJSONResBody {
  message: string;
  system?: boolean;
}

export interface PostRouteJSONReqBody {
  age?: number;
  email: string;
  name: string;
}

export interface GetRouteJSONResBody {
  appName: string;
  appVersion: string;
}





  export const getRoute = <TData = AxiosResponse<GetRouteJSONResBody>>(
    params?: GetRouteParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/route`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const postRoute = <TData = AxiosResponse<PostRouteJSONResBody>>(
    postRouteJSONReqBody: PostRouteJSONReqBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/route`,
      postRouteJSONReqBody,options
    );
  }

export type GetRouteResult = AxiosResponse<GetRouteJSONResBody>
export type PostRouteResult = AxiosResponse<PostRouteJSONResBody>
